cache:
  paths:
    - node_modules/
before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass
deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - sshpass -V
    - export SSHPASS=$USER_PASS
    - sshpass root@46.101.109.16:/srv/projects/shortstories-frontend
    - git pull
    - yarn
    - yarn build:prod
    - pm2 restart all
