image: ubuntu
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan 46.101.109.16 >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
deploy_production:
  type: deploy
  script:
    - ssh root@example.com "cd /srv/projects/shortstories-frontend/ && git checkout master && git pull origin master && yarn && yarn build:prod && pm2 restart all && exit"
  only:
    - master
