cache:
  paths:
    - node_modules/
before_script:
 - apt-get update -qq && apt-get install -y -qq sshpass
deploy_production:
  type: deploy
  script:
    - sshpass -V
    - export SSHPASS=$USER_PASS 
    - sshpass ssh -o StrictHostKeyChecking=no root@46.101.109.16 "cd /srv/projects/shortstories-frontend && git checkout master && git pull origin master && exit"
  only:
    - master
